# Generated by Django 3.0.4 on 2020-11-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrahphApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='Sales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='Units',
            field=models.IntegerField(),
        ),
    ]
